name: Generate Love2D Game File

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Generate .love File
    runs-on: ubuntu-latest

    steps:
      - name: Love actions bare package
        uses: love-actions/love-actions-core@v1.1.0

      - name: Upload .love File
        uses: actions/upload-artifact@v4
        with:
          name: game
          path: game.love
            
